FROM gcvcg/colmap:latest
ARG PYTHON_VERSION=3.8
RUN apt-get update -y
RUN apt-get install -y unzip wget software-properties-common python3-distutils
RUN add-apt-repository ppa:deadsnakes/ppa && \
    apt-get -y update && \
    apt-get install -y python${PYTHON_VERSION}
RUN wget https://bootstrap.pypa.io/get-pip.py && python${PYTHON_VERSION} get-pip.py
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${PYTHON_VERSION} 1
RUN git clone --recursive https://github.com/cvg/Hierarchical-Localization/ /hloc
WORKDIR /hloc
RUN pip3 install --upgrade pip setuptools
RUN python3 -m pip uninstall -y distro-info
# RUN pip3 install --upgrade setuptools==58.3.0
RUN pip3 install -r requirements.txt
RUN pip3 install -e .