FROM gcvcg/colmap:latest
ARG PYTHON_VERSION=3.8

RUN apt-get update -y
RUN apt-get install -y unzip wget software-properties-common python3-distutils python3-dev
RUN add-apt-repository ppa:deadsnakes/ppa && \
    apt-get -y update && \
    apt-get install -y python${PYTHON_VERSION}
RUN wget https://bootstrap.pypa.io/get-pip.py && python${PYTHON_VERSION} get-pip.py
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${PYTHON_VERSION} 1


RUN apt-get install -y libhdf5-dev
RUN pip3 install --upgrade pip setuptools==58.3.0

# RUN ln -s /usr/lib/ /usr/include
# RUN bash -c 'whereis python3'
# Installing pyceres
RUN git clone --branch v1.0 --recursive https://github.com/cvg/pyceres.git  /pyceres
WORKDIR /pyceres
RUN pip3 install -e .

# Installing pycolmap
RUN git clone --branch v0.4.0 --recursive https://github.com/colmap/pycolmap.git /pycolmap
WORKDIR /pycolmap
RUN pip3 install -e .

# Installing pixsfm
RUN git clone --recursive https://github.com/cvg/pixel-perfect-sfm /pixel-perfect-sfm
WORKDIR /pixel-perfect-sfm
RUN pip3 install -r requirements.txt
RUN pip3 install Pillow==9.5.0

RUN git clone --recursive https://github.com/cvg/Hierarchical-Localization/
RUN cd Hierarchical-Localization && pip3 install -e .

RUN pip3 install -e .
